### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by SWORDSMENPLAYZ** [tungstonminer/french-vanilla#36]
### Please answer the following questions

*What is your experience playing modded Minecraft?*
I usually do not play modded Minecraft because I create my own mods, usually solving vanilla issues, and I have used Tinkers Constuct for a while now. I love modded Minecraft and playing it with people who love it also will be a dream come true.

*Have you successfully been able to play *this mod pack* in single-player?*
Yes

*What is your Minecraft username?*
SWORDSMENPLAYZ
### Please re-state the server rules in your own words
1. No hacking
2. No griefing
3. No stealing
4. No attacking without consent
5. No destroying Terrian without a purpose
### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered once per day, so you should generally receive a response in less than 24h.  In the meantime, you can set up your Minecraft instance to access the server at:

`austere-caves.sparkedservers.us`

Finally, it is *highly recommended* that you read [the wiki](https://github.com/tungstonminer/french-vanilla/wiki) for the modpack.  There are *a lot* of changes to world generation, mob spawning, ore placement, recipes and general game mechanics which will be very confusing otherwise.  **IN PARTICULAR**, please read the section on [etiquette](https://github.com/tungstonminer/french-vanilla/wiki/Etiquette) for some of the basic expectations that have developed among the players so far.

**Comment by tungstonminer** [comment]
My appologies for taking so long to get to this!  You should be all set to get in.  If you run into any problems, please ask on the Discord server.
